export const astrologers = [
  {
    id: 1,
    name: 'Aacharya Aaditya',
    image: 'https://placehold.co/80x80/FFF7ED/F97316?text=A',
    isOnline: true,
    expertise: ['Vedic Astrology', 'Tarot'],
    languages: ['Hindi', 'English'],
    experience: 10,
    price: 15,
    rating: 4.9,
    calls: 1876,
    chats: 2345,
  },
  {
    id: 2,
    name: 'Vidushi M',
    image: 'https://placehold.co/80x80/F0F9FF/0EA5E9?text=V',
    isOnline: false,
    expertise: ['Palmistry', 'Numerology'],
    languages: ['Hindi'],
    experience: 8,
    price: 12,
    rating: 4.8,
    calls: 1502,
    chats: 1987,
  },
  {
    id: 3,
    name: 'Rishi Kumar',
    image: 'https://placehold.co/80x80/ECFDF5/10B981?text=R',
    isOnline: true,
    expertise: ['Vastu', 'Face Reading'],
    languages: ['English', 'Tamil'],
    experience: 15,
    price: 20,
    rating: 4.95,
    calls: 3109,
    chats: 4511,
  },
  {
    id: 4,
    name: 'Astrologer Neha',
    image: 'https://placehold.co/80x80/FFF1F2/F43F5E?text=N',
    isOnline: true,
    expertise: ['Tarot Reading', 'Love & Relationship'],
    languages: ['English'],
    experience: 5,
    price: 18,
    rating: 4.85,
    calls: 980,
    chats: 1230,
  },
  {
    id: 5,
    name: 'Pandit Sharma',
    image: 'https://placehold.co/80x80/EFF6FF/3B82F6?text=P',
    isOnline: false,
    expertise: ['Career Astrology', 'Kundali Matching'],
    languages: ['Hindi', 'Punjabi'],
    experience: 20,
    price: 25,
    rating: 4.9,
    calls: 4500,
    chats: 5100,
  },
  {
    id: 6,
    name: 'Guru Simran',
    image: 'https://placehold.co/80x80/F5F3FF/8B5CF6?text=G',
    isOnline: true,
    expertise: ['Numerology', 'Vedic Astrology'],
    languages: ['Hindi', 'English', 'Gujarati'],
    experience: 12,
    price: 17,
    rating: 4.92,
    calls: 2500,
    chats: 3200,
  },
];

export const liveShows = [
  { id: 1, title: 'Future of Your Relationship', host: 'Astrologer Neha', viewers: '2.1k', image: 'https://placehold.co/250x160/F43F5E/FFFFFF?text=LIVE' },
  { id: 2, title: 'Career Growth Secrets', host: 'Rishi Kumar', viewers: '1.8k', image: 'https://placehold.co/250x160/10B981/FFFFFF?text=LIVE' },
  { id: 3, title: 'Weekly Tarot Reading', host: 'Vidushi M', viewers: '3.2k', image: 'https://placehold.co/250x160/0EA5E9/FFFFFF?text=LIVE' },
  { id: 4, title: 'Vastu for Home', host: 'Pandit Sharma', viewers: '1.5k', image: 'https://placehold.co/250x160/3B82F6/FFFFFF?text=LIVE' },
  { id: 5, title: 'Numerology & Your Name', host: 'Guru Simran', viewers: '2.5k', image: 'https://placehold.co/250x160/8B5CF6/FFFFFF?text=LIVE' },
  { id: 6, title: 'Love Compatibility', host: 'Aacharya Aaditya', viewers: '2.9k', image: 'https://placehold.co/250x160/F97316/FFFFFF?text=LIVE' },
];

export const specialShows = [
  { id: 1, name: 'Astrologer Neha', image: 'https://placehold.co/300x128/FFF1F2/F43F5E?text=Live+Session', question: 'Will he marry you?', liveWithHost: 'Rishi Kumar', liveWithHostImage: 'https://placehold.co/32x32/E0E7FF/4338CA' },
  { id: 2, name: 'Aacharya Aaditya', image: 'https://placehold.co/300x128/FFF7ED/F97316?text=Live+Session', question: 'When will I get a job?', liveWithHost: 'Vidushi M', liveWithHostImage: 'https://placehold.co/32x32/E0E7FF/4338CA' },
  { id: 3, name: 'Guru Simran', image: 'https://placehold.co/300x128/F0F9FF/0EA5E9?text=Live+Session', question: 'Is my partner cheating?', liveWithHost: 'Pandit Sharma', liveWithHostImage: 'https://placehold.co/32x32/E0E7FF/4338CA' },
  { id: 4, name: 'Rishi Kumar', image: 'https://placehold.co/300x128/ECFDF5/10B981?text=Live+Session', question: 'What does my future hold?', liveWithHost: 'Astrologer Neha', liveWithHostImage: 'https://placehold.co/32x32/E0E7FF/4338CA' },
  { id: 5, name: 'Vidushi M', image: 'https://placehold.co/300x128/F5F3FF/8B5CF6?text=Live+Session', question: 'Wealth & Finance Forecast', liveWithHost: 'Aacharya Aaditya', liveWithHostImage: 'https://placehold.co/32x32/E0E7FF/4338CA' },
  { id: 6, name: 'Pandit Sharma', image: 'https://placehold.co/300x128/EFF6FF/3B82F6?text=Live+Session', question: 'Your Health in 2026', liveWithHost: 'Guru Simran', liveWithHostImage: 'https://placehold.co/32x32/E0E7FF/4338CA' },
];